### ISSUE TITLE
Dynamic routing bug

### ISSUE THREAD

**Issue by Kieran-Muller-Ent** [carbon-design-system/ibm-dotcom-library-nextjs-template#6]
When utilising dynamic routing, the page renders but an error is thrown upon first navigation to dynamic route: 
![Screenshot 2020-07-28 at 11 46 44](https://user-images.githubusercontent.com/57447348/88656318-04c0c400-d0c8-11ea-983a-c14e236dd599.png)

Upon refresh, the page does not render and an error is displayed: 
![Screenshot 2020-07-28 at 11 47 41](https://user-images.githubusercontent.com/57447348/88656414-2c179100-d0c8-11ea-82f4-2a265022edb7.png)

SOLUTION

inside of the next.config.js, inside of the module.exports there is a key value pair called assetPrefix. By removing this from the withCSS, the errors ceased and the dynamic routing worked flawlessly.

References:
https://stackoverflow.com/questions/52195494/next-js-next-webpack-hmr-request-404

**Comment by RaphaelAmadeu** [comment]
This was fixed on the latest version of master. Thank you!
